name: dispatch-on-release
on: push

jobs:
  post-on-push:
    name: Post on push
    runs-on: ubuntu-latest
    steps:
      - name: Display the path
        run: echo $PATH
        shell: bash
      - name: Check out source?
        uses: actions/checkout@v2
      - name: Sends a thing someplace
        run: |
          curl \
            -X POST \
            -H "Accept: application/vnd.github.v3+json" \
            https://hookb.in/yDZnE8VJlPtG9yjj91km \
            -d '{"event_type": "my_event"}'

