name: dispatch-on-release
on:
  release:
    types: [released]

jobs:
  post-on-release:
    name: Post on release
    runs-on: ubuntu-latest
    steps:
      - name: Displays release details
        run: |
          jq '.[].browser_download_url ${{ github.event.release.assets }}'
      - name: Sends a thing someplace
        run: |
          curl \
            -X POST \
            -H "Accept: application/vnd.github.v3+json" \
            https://hookb.in/yDZnE8VJlPtG9yjj91km \
            -d '{"event_type": "my_event"}'