name: dispatch-on-release
on:
  release:
    types: [released]

jobs:
  post-on-release:
    name: Post on release
    runs-on: ubuntu-latest
    steps:
      - name: Stores incoming version
        run: |
          version=`echo ${{ github.event.release.tag_name }} | sed s/v//`
          echo "version=$version" >> $GITHUB_ENV
      - name: Downloads file and computes sha256
        run: |
          curl -L -o subo.tar.gz https://github.com/suborbital/subo/archive/v${{ env.version }}.tar.gz
          suboSHA=`sha256sum subo.tar.gz | cut -c -64`
          rm subo.tar.gz
          echo "sha=$suboSHA" >> $GITHUB_ENV
      - name: Sends a thing someplace
        run: |
          curl \
            -X POST \
            -H "Accept: application/vnd.github.v3+json" \
            https://hookb.in/aBkdwDqjD9sXQ9kkQ8Ox \
            -d '{"event_type": "subo_release", "client_payload": {"sha": "${{ env.sha }}","tag": "${{ env.version }}", "release_url": "${{ github.event.release.html_url}}"}}'


# cat test.json | jq '.assets | .[] | .name | select(test("-darwin-amd64.tar.gz$"))'